[tool.poetry]
name = "dme22"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
pandas = "^1.4.4"
numpy = "^1.23.3"
scipy = "^1.9.1"
matplotlib = "^3.5.3"
seaborn = "^0.12.0"
polars = "^0.14.10"
click = "^8.1.3"
pydantic = "^1.10.2"
logger = "^1.4"
loguru = "^0.6.0"


[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
jupyter = "^1.0.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
